services:
  postgres:
    image: postgres:16
    container_name: mon-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: monuser
      POSTGRES_PASSWORD: tototatatiti
      POSTGRES_DB: pokedex
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monuser -d pokedex"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: